### ISSUE TITLE
Geänderte Start Bytes?

### ISSUE THREAD

**Issue by rufinus** [greenMikeEU/SmartMeterEVNSagemcom-T210-D#15]
Servus Mike,

funktioniert dein skript noch? Es sieht aus als hätte die EVN am 2. Mai die Startbytes geändert.

es sieht aus als wäre das startbyte nun 68fafa68

kannst du das bestätigen?

lg

**Comment by greenMikeEU** [comment]
Hallo,
ich habe nur die Information von der EVN bekommen das ein Fehler im Protokoll gefixt wird. Das wurde mit 02.05.2023 ausgerollt  und soll am Display abgelesen werden können. (0.2.0.01 V0450)

Ich bin derzeit Unterwegs und werde am Wochenende an einer Lösung arbeiten.

Wenn jemand eine Lösung hat bitte Informieren oder einen Pull Request machen.

LG Michael

![20230503_080202](https://user-images.githubusercontent.com/25603398/235961852-2e954d7a-0463-4803-a3f1-3bf5da46c77c.jpg)

**Comment by Matthias-V2** [comment]
Vielen Dank für deine/eure Mühen :).
Die EVN machts einem ja nicht einfach…

**Comment by geek-at** [comment]
In der Doku von der EVN wurden die Startbytes  tatsächlich geändert. 68fafa68 sind jetzt korrekt.

![image](https://user-images.githubusercontent.com/2073090/235964744-40823f7e-8ce1-42a0-9830-e85382471ca0.png)

Da der rest dann aber nicht entschlüsselt werden kann, nehme ich an, dass es noch mehr Änderungen gab. Ich versuche mir mal einen Überblick zu schaffen

**Comment by rufinus** [comment]
bin schon einen schritt weiter... das XML ist nicht mehr komplett sondern besteht nun auch aus teilen..
da wir keine existenz prüfung haben bricht das skript relativ häufig ab.

```
XML:  <DataNotification>
  <LongInvokeIdAndPriority Value="800048A6" />
  <DateTime Value="07E705030311210500FF8882" />
  <NotificationBody>
    <DataValue>
      <Structure Qty="23" >
        <OctetString Value="07E705030311210500FF8882" />
        <OctetString Value="0100010800FF" />
        <UInt32 Value="015833D9" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1E" />
        </Structure>
        <OctetString Value="0100020800FF" />
        <UInt32 Value="00C0774B" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1E" />
        </Structure>
        <OctetString Value="0100010700FF" />
        <UInt32 Value="0000089E" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1B" />
        </Structure>
        <OctetString Value="0100020700FF" />
        <UInt32 Value="00000000" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1B" />
        </Structure>
        <OctetString Value="0100200700FF" />
        <UInt16 Value="092E" />
        <Structure Qty="02" >
          <Int8 Value="FF" />
          <Enum Value="23" />
        </Structure>
        <OctetString Value="0100340700FF" />
        <UInt16 Value="0944" />
        <Structure Qty="02" >
          <Int8 Value="FF" />
          <Enum Value="23" />
        </Structure>
        <OctetString Value="0100480700FF" />
        <UInt16 Value="094B" />
        <Structure Qty="02" >
          <Int8 Value="FF" />
          <Enum Value="23" />
        </Structure>
        <OctetString Value="01001F0700FF" />
        <UInt16 Value="036F" />
        <Structure Qty="02" >
          <Int8 Value="FE" />
          <Enum Value="21" />
        </Structure>
        <OctetString Value="0100330700FF" />
        <UInt16 Value="0093" />
        <Structure Qty="02" >
          <Int8 Value="FE" />
          <Enum Value="21" />
        </Structure>
        <OctetString Value="0100470700FF" />
      </Structure>
    </DataValue>
  </NotificationBody>
</DataNotification>

Fehler:  list index out of range
Daten:  68fafa6853ff000167db085341475905e8b4cb81f82000a62c9f4590a93c828494742e7c19f12c7ed1d1db014e787d263bb665895e099d42903aac71a4660cf65f279a4b97821d50868d7a399c4c469d60902d22df58ed318b65e4c04f7c630acb93edd99725a276196b52ce10602155991fe985ca051f1c82756b175d2c52aa043c72bbf65f5f3d97c233d1fd6c60c76ce2bf07d08f538c1d7427782b3b0dddc38661dd4284a6cb3e86f9


XML:  <DataNotification>
  <LongInvokeIdAndPriority Value="800048A7" />
  <DateTime Value="07E705030311210A00FF8882" />
  <NotificationBody>
    <DataValue>
      <Structure Qty="23" >
        <OctetString Value="07E705030311210A00FF8882" />
        <OctetString Value="0100010800FF" />
        <UInt32 Value="015833DB" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1E" />
        </Structure>
        <OctetString Value="0100020800FF" />
        <UInt32 Value="00C0774B" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1E" />
        </Structure>
        <OctetString Value="0100010700FF" />
        <UInt32 Value="0000047E" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1B" />
        </Structure>
        <OctetString Value="0100020700FF" />
        <UInt32 Value="00000000" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1B" />
        </Structure>
        <OctetString Value="0100200700FF" />
        <UInt16 Value="0938" />
        <Structure Qty="02" >
          <Int8 Value="FF" />
          <Enum Value="23" />
        </Structure>
        <OctetString Value="0100340700FF" />
        <UInt16 Value="093B" />
        <Structure Qty="02" >
          <Int8 Value="FF" />
          <Enum Value="23" />
        </Structure>
      </Structure>
    </DataValue>
  </NotificationBody>
</DataNotification>

Fehler:  list index out of range
Daten:  68fafa6853ff000167db085341475905e8b4cb81f82000a62ca01aefc7f1c7cc65c3c100e3a1893e8c10acab596a86d77eed292707d26037f979f49e6d0be3a0609b82bc94fceeb676e5de3fa5859054d3e589be515cd0ddf39c684d989dc938539b313bc9d4b556c1ece65f44


XML:  <DataNotification>
  <LongInvokeIdAndPriority Value="800048A8" />
  <DateTime Value="07E705030311210F00FF8882" />
  <NotificationBody>
    <DataValue>
      <Structure Qty="23" >
        <OctetString Value="07E705030311210F00FF8882" />
        <OctetString Value="0100010800FF" />
        <UInt32 Value="015833DD" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1E" />
        </Structure>
        <OctetString Value="0100020800FF" />
        <UInt32 Value="00C0774B" />
        <Structure Qty="02" >
          <Int8 Value="00" />
          <Enum Value="1E" />
        </Structure>
        <OctetString Value="0100010700FF" />
      </Structure>
    </DataValue>
  </NotificationBody>
</DataNotification>

Fehler:  list index out of range
Daten:  68fafa6853ff000167db085341475905e8b4cb81f82000a62ca182a25107855a4114a6633f6122ca176afef1f216f652


XML:  <DataNotification>
  <LongInvokeIdAndPriority Value="800048A9" />
  <DateTime Value="07E705030311211400FF8882" />
  <NotificationBody>
    <DataValue>
      <Structure Qty="23" >
      </Structure>
    </DataValue>
  </NotificationBody>
</DataNotification>


```

wie man hier schön sieht sind die DataValu im NotificationBody jetzt nicht immer vollständig. lässt man es lange genug laufen kkommt auch mal ein komplettes paket - aber eher selten leider.

**Comment by rufinus** [comment]
Das ist so ein dermassen bescheidenes XML datenpaket ...

da wir uns nicht mehr auf komplette pakete verlassen können müssen wir die werte anhand des "OctetString value" identifizieren.
das ist immer jener wert der direkt vor UInt32 bzw UInt16 kommt. Warum das keine hirachische Struktur haben kann?

Python ist leider nicht meine "muttersprache" aber ich denke wir müssten das XML zeile für zeile durchgehen.
wenn aktuelle zeile einen bekannten OctetSTring wert hat dann ist der nächste UInt32 oder UInt16 Wert ein gewünschter Value.

ich hatte vorhin glück und hab ein komplettes paket bekommen.

Hier der Table für die Werte:
```
0100010800FF => UInt32 WirkenergiePA
0100020800FF => UInt32 WirkenergieNA
0100010700FF => UInt32 MomentanleistungPA
0100020700FF => UInt32 MomentanleistungNA

0100200700FF => Uint16 SpannungL1A
0100340700FF => UInt16 SpannungL2A
0100480700FF => UInt16 SpannungL3A
01001F0700FF => UInt16 StromL1A
0100330700FF => UInt16 StromL2A
0100470700FF => UInt16 StromL3A
01000D0700FF => UInt16 ??? (LeistungsfaktorA?)
```

**Comment by bausi2k** [comment]
Was ich spannend finde ist, dass immer wieder aber doch Werte kommen? 
Kann es sein, dass es auch neue Werte gibt? Am Smartmeter selbst gibt es mittlerweile sehr viele Daten, die angezeigt werden.

**Comment by cbrandstaetter** [comment]
Anstelle von 
frame = daten[52:560]
habe ich 
frame = daten[52:512]
genommen.
Das hat bei mir die Häufigkeit von korrekten Datenpaketen deutlich erhöht.

**Comment by ErichFreitag** [comment]
@cbrandstaetter - mag sein, aber die gesamte (serielle) Datenlänge beträgt 564 bytes, somit keine Lösung

**Comment by geek-at** [comment]
> Das hat bei mir die Häufigkeit von korrekten Datenpaketen deutlich erhöht.

Ja bei mir auch @cbrandstaetter . Davor war ca jedes 10. Datenpaket in Ordnung, jetzt mit deinem fix jedes 2. ca

**Comment by rufinus** [comment]
@cbrandstaetter ja kann ich bestätigen - läuft mit 512 zuverlässiger. interessant.

**Comment by cbrandstaetter** [comment]
Das läuft bei mir jetzt gut und liefert im 99% der Fälle korrekte Daten:
https://github.com/cbrandstaetter/EvnSmartmeterMQTTinfluxDB/blob/main/EvnSmartmeterMQTTinfluxDB.py

**Comment by mrantonSG** [comment]
> Das läuft bei mir jetzt gut und liefert im 99% der Fälle korrekte Daten:
> https://github.com/cbrandstaetter/EvnSmartmeterMQTTinfluxDB/blob/main/EvnSmartmeterMQTTinfluxDB.py

Kann ich bestätigen - läuft gut

**Comment by frog-fest** [comment]
Kann jemand bestaetigen, dass die Checksumme (vorletztes Datenbyte) nicht mehr stimmt? Im Beispiel vom EVN PDF stimmt es hingegen.

Hab den gesamten Datenstring ohne die letzten beiden Bytes schon zig mal hier geprueft: https://www.scadacore.com/tools/programming-calculators/online-checksum-calculator/ 

CheckSum8 Modulo 256 muss man sich anschauen. Stimmt bei keinem Datensatz. Hab aber leider keinen alten zum vergleichen.

Keine Ahnung ob das etwas mit dem Problem an sich zu tun hat, aber eine Checksumme sollte mMn schon richtig sein. Oder ich hab irgendwo einen Denkfehler... :)

**Comment by cbrandstaetter** [comment]
Weil mir unklar ist, über welchen Bereich die Checksumme gerechnet ist, habe ich alle möglichen Ranges ausprobiert. Es findet sich aber keine Range bei der die Checksumme immer passen würde.

**Comment by Pillmayr** [comment]
Auf diesem Weg einfach mal herzlichen Dank an alle Beteiligten für die tolle und vor allem SCHNELLE Reaktion zu dem Problem und das so schnell eine Übergangslösung bereitgestanden ist. THX!!

**Comment by frog-fest** [comment]
> funktioniert bei mir auch - nur muss ich das script öfters starten bis es läuft, es bricht ab wenn es am anfang keine richtigen daten bekommt.

Vielleicht hilft dir ja das? Hier lese ich ab dem Header ein... (einach zum Testen deine def recv Sektion kommentieren und die hier probieren, ggf. den Namen 'recv' anpassen)

`
dataHeader = b'\x68\xFA\xFA\x68'

def recv(serIn):
    readBuffer = b''
    while True:
        try:
            start = serIn.read_until(dataHeader)
            #we don't use start, to ignore a possibly shiftet offset
            readBuffer = dataHeader
            readBuffer += serIn.read(278)
            #print(f"Datensatz empfangen, Länge: {len(readBuffer)}")
            #print(f"Daten: {readBuffer.hex()}")
            break
        except:
            pass
            print("serial read error")
    return readBuffer
`

**Comment by frog-fest** [comment]
> Weil mir unklar ist, über welchen Bereich die Checksumme gerechnet ist, habe ich alle möglichen Ranges ausprobiert. Es findet sich aber keine Range bei der die Checksumme immer passen würde.

Die Checksumme wird ueber den ganzen Datensatz gemacht, ausser die letzten beiden Bytes natuerlich (also ohne Checksumme und ohne Stop Byte). Probiers mit dem Link und dem Beispiel aus dem EVN PDF aus, da stimmt die Checksumme naemlich.
https://www.scadacore.com/tools/programming-calculators/online-checksum-calculator/ (siehe auch mein Posting)

**Comment by georg-x** [comment]
@cbrandstaetter Herzlichen Dank. Die Version funktioniert auch für mich und habe ich auch in meinen Fork (mit Anbindung an thingspeak) übernommen.

**Comment by greenMikeEU** [comment]
@cbrandstaetter bitte melde dich bei mir support@michaelreitbauer.at
Und ein großes Danke an die ganzen Unterstützer
Ich habe auch schon ein großes Update rumliegen welches noch getestet wird und dann hier gepostet
