### ISSUE TITLE
Invalid Start Bytes... waiting

### ISSUE THREAD

**Issue by michaelhenningersrb** [greenMikeEU/SmartMeterEVNSagemcom-T210-D#2]
Hallo,

erstmal Danke für dieses hervorragende Projekt.
Ich habe versucht alles nachzubauen.
Verbindung zum MQTT Broker funktioniert.

Jedoch bekomme ich beim Ausführen immer wieder "Invalid Start Bytes... waiting".

Ich verwende folgendes Kabel: https://www.amazon.de/gp/product/B08GWZTNM3/ref=ppx_yo_dt_b_asin_title_o06_s01?ie=UTF8&th=1

@greenMikeEU Hättest du eventuell einen Tipp für mich?

SG Michael

**Comment by greenMikeEU** [comment]
Hallo, 
ich habe verwende das Kabel nicht daher kann ich keine Auskunft darüber geben. In meinem Blog ist ein Adapter verlinkt der auf jeden fall funktioniert.
https://www.michaelreitbauer.at/sagemcom-t210-d-auslesen-smart-meter-evn/

Sie könnten mir auch einen Datenframe zukommen lassen und ich sehe mir den dann genauer an 
Welchen zähler verwenden sie ?

**Comment by michaelhenningersrb** [comment]
Ok, danke, wenn ichs nicht hinbekomme werd ich mir wohl genau den Adapter bestellen.

Ich habe den `Sagecom T210-D`.

Zum Frame: 
Ich bekomme anfang immer `00` und danach `""` also leerstring.

Ich denke dass das Kabel einfach nicht dafür ausgelegt ist. Ich glaub mein Kabel ist nur ein USB zu Serial converter.
Macht der MBUS Adapter das selbe? Oder ist da nicht nur ein Logik Converter verbaut?


SG

**Comment by greenMikeEU** [comment]
MBus hat auch andere Spannugspegel von 36 und 24 V eventuell passt da was nicht mit deinem Umsetzers.

Sie können mir auch eine E-Mail schreiben dann kann ich über TeamViewer helfen oder wir telefonieren kurz.

**Comment by Rattlesnake1980** [comment]
@michaelhenningersrb : Das Kabel oben habe ich auch beim ersten Versuch verwendet und gleich wieder zurückgeschickt, da nicht geeignet für den Sagecom T210-D. Mit USD zu Serial Converter hatte ich auch keinen Erfolg. 
Erst mit dem in der Projektbeschreibung angeführten MBUS zu USB Slave Modul. Seitdem läuft's!

**Comment by michaelhenningersrb** [comment]
Vielen Dank für deine Hilfsbereitschaft!!!!

Ich hab mir mal den Adapter aus deiner Bauteilliste bestellt. Kabel sollt ich noch haben.
Bestellung sollte nächste Woche irgendwann kommen.

@Rattlesnake1980 Danke für den Hinweis! Echt Zufall dass ich genau den gleich Fehler mach ;)

Ich halte dich auf dem Laufenden!

P.S.: Gibts irgendwo ein gscheites Forum bzw. einen Blog in dem man über solche Themen fachsimpeln kann?

**Comment by greenMikeEU** [comment]
Ich werde denn Fall schließen und als gelöst deklarieren. 
Auf meinen Blog kann man etwas fachsimpeln würde auf keinen Fall schaden. Aber ist halt kein richtiges Forum 😅

**Comment by dirkNDH** [comment]
Falls die MBUS Adapter nicht lieferbar sind oder jemand lieber selber bastelt: Kann man selber machen mit 2 Optokopplern, ein paar anderen normalen Bauteilen und einem Arduino Nano (oder ähnlich). Schaltung und Programm kann ich gerne beisteuern. Am Ende liefert der Arduino am USB Port die gewünschten Daten.

**Comment by greenMikeEU** [comment]
Hallo könntest du mir die Infos schicken mich interessiert die ganze Thematik

mreitbauer@gmx.net

**Comment by dieterlind** [comment]
@dirkNDH 
Kannst du mir vielleicht bezüglich Nachbau auch kurz schreiben. dieter.lindermaier@gmx.at. Danke!

**Comment by michaelhenningersrb** [comment]
Kleines Update zu meinem bestellten MBUS Adapter. Leider bei allen Verkäufern auf Amazon nicht mehr vorrätig :(

Habe jetzt in China bestellt. Hier der Link:  https://deu.grandado.com/products/usb-zu-mbus-slave-modul-mbus-master-slave-kommunikation-debugging-bus-uberwachung?variant=UHJvZHVjdFZhcmlhbnQ6NTQxNDk5NTc

Hat jemand Erfahrung mit einem anderen USB Adapter? Bzw einer einfachen Verwendung eines ESP?

**Comment by greenMikeEU** [comment]
Hallo,

**Comment by dieterlind** [comment]
Nachdem die Lieferung von Aliexpress doch relativ lang dauert habe ich jetzt mal alternativ das Teil lt. Link bestellt: https://www.willhaben.at/iad/kaufen-und-verkaufen/d/smartmeter-kundenschnittstelle-oesterreich-slovenien-527601477. Klinkt eigentlich sehr interessant, weil kein zusätzliches Gerät mehr benötigt wird. Ich bekomme es morgen und kann ja berichten ..

**Comment by michaelhenningersrb** [comment]
@dieterlind Klingt echt interessant. Bitte berichte ;)

**Comment by dieterlind** [comment]
Kleines Update zu dem von mir oben verlinkten Gerät. Ist gestern gekommen. Gemäß Dokumentation konfiguriert. Mittels MQTT in meinen IoBroker eingebunden. Funktioniert auf Anhieb.
Einzige Herausforderung: Man braucht dort wo das Teil installiert ist ein WLAN ... kann manchmal an der Grundgrenze wohl ein Problem sein ....

**Comment by geek-at** [comment]
Hallo und danke für das Projekt @greenMikeEU 

Ich hab auch das Invalid start bytes Problem und wenn ich mir eine sequenz ausgeben lasse, sieht die so aus

```
0000f88000787878807878f800f80080f80080f8800078f878f80080788080788080f878f878f87800f8f87880808000f880f8f880f8f8787800f88000807880f8007880f88000f8f87880f80080f880f878f87878f88078800000f8807880f8000000f878787878f8780080f80000f8f880788078f8788080787800f8008078808078780078008078f87800808000f8f880787800f800008078788078f880f8007800f8f8807880807878f878f8f8f87880780000f8008000f8800078f8f80078f88078787800f87878f8f880f800007800788000f8f88000f87800807880f87880f8f8787880f8787878f8f87880f80078007880800000f878f80078007880f8f880f800f8f88000f88000788078f878808000f88078f8780080f800000000808080f8780080787878780000780078808080007880f8f878f800787878007800f80080f8787880f878807878008080f800f8f88080f800780000f88000787800f8800080808078f8000078f80080f800788000788078f880f878f800f880f8f8f878f8f8f878808080800078f880780078f8f87878788078800078f8f8808000808078787878800000f8f8f8780078f8808078808000f800788078008000f880f878f880787800f8f8f87878f800f8f878800000f8007878f8800078807878808080780078f8f87878808080807800f8f87800780000f8f8f88078f878000078f880f88000f8f8f800f800000080007800f8f80078807800f8f8787800f8f8f88078f87878f880f8f8f8f87800f880787880f800807878780000f87800007878780080000080f800f878f80000f8808080787878780000808080f87878000080f8f87800f8f8f8008078007800f8f87878788078f800f878f800787878f87800f878f8007800f87880f8000000f880007880808080007800787880780078f8780078f8f8807880f88000788080780080f8f88000f8808080f8780080808080f87880f87800f80080f8780080f878000080f880f800808078807800f8788080f8f880808078f87800f8f87878788080007878f880f878f88000008078808000780078f87880f8f87880808000787878f8f880787880f8f8f878008078f880f8f800008080f878f87878f8f87880000000808078f800008078f878008080f8787878f87878f878807800f8780078f878f80078f880f8f878f878f800008078800000807800f8f87800780000f8f8f88078f878000078f880f8f880788078f8808080f8f880f88080787880807880007800f878807800f8f8787800f8f8f88078f87878f880f8f8f8f87800f880787880f800807878780000f87800007878780080000080f8000080f878f87878007880f880007800787800f800007880807880f8000000f8f880808080f8f878000080f8f878f8f800f800f8808080f80078f878f8f8f87880008080800080f8f8808080787878f878f8f8f87878808078f878008000f800788080f878f880f8f8008000787800f87878f87880787878f8f88080008080800078007880f800f8008000f8f88000f8008000f880008000807800f878f880f87878807878808078f878f87800f87800f878f8787800f8808078788078f878f800f8008000f8807878788000f8008078787800800000f800f8f8807800800080f8f880808078f8f8000000f88080808078f80080f87878f880f800f8f87878007880f8808078f880f8787880f8f8f880807880007878808080780000f80000f80078800080f8f880808078f878f88080808078787800f800f87880f8807880807878f880807878f8787800f80000f800007880008000808078800000f8800080808078807800808080f878787878f878f88000f8f8008000780078f87878f880f88078808078807878808000f880f8f80000f8807878808080f878f800f878000080f8f8008078f878f878f8007880f800f8f800800078f878788000007878f80078780000000080f878788080808080808080780078008080787878787800f8f8807878807878000000f878f80078f8f8f8f88080f878f8f8f8f880f8787800787880780078807800f8788000000080000078f8f8f8f800f8f80080007880f880f8787880807800f8f87800780000f8f8f88078f878000078f880f800f8808080f8f880f8008000800078f878807878f8808078
```

Da er ja nach `68010168` sucht schlägt es hier fehl, aber vielleicht hab ich auch das mbus modul (genau deines aus dem Blog) falsch angesteckt?

Laut der Grafik im Repo muss mans ja an + und - anhängen, aber am Gerät selbst sind gar keine Infos, welches Terminal jetzt plus und minus ist. ![](https://pictshare.net/qj4vdw.png)

Auch auf den Produktseiten findet man da nichts. Hat wer einen Tipp für mich? :D
![](https://raw.githubusercontent.com/greenMikeEU/SmartMeterEVNSagemcom-T210-D/main/RJ12-Pinout.PNG)
