### ISSUE TITLE
Fehler in V2.0

### ISSUE THREAD

**Issue by Daffy2905** [greenMikeEU/SmartMeterEVNSagemcom-T210-D#20]
Hallo!

Habe jetzt gerade versucht die Version 2.0 zu verwenden. Installation mittels sudo install.sh bzw. sudo einrichtung.sh liefen einwandfrei durch, beim manuellen Start des Auslesescript.py kommt folgende Fehlermeldung auf der Shell:

pi@raspberrypi:~ $ sudo python3 AusleseSkript.py
Traceback (most recent call last):
  File "AusleseSkript.py", line 32, in <module>
    config = json.load(open(configFile))
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 17 (char 34)

Wer das gleiche bzw. ne Idee?
BG David

**Comment by greenMikeEU** [comment]
Hallo,

schaut nach einem Fehler im config File aus

LG Michael

**Comment by Daffy2905** [comment]
Läuft :-) Fehler war, dass ich bei den Abfragen angenommen habe, dass die vorgeschlagenen Werte (/dev/ttyUSB0 etc.) mittels ENTER auch übernommen werden. Man muss die Werte manuell eintippen, dann läufts!
Jetzt kommt ein Fehler im ioBroker, welcher bei mir als MQTT Broker fungiert, wenn sich der SmartMeterClient anmeldet:

  | Client [SmartMeter] connection closed: Error: read ECONNRESET

Daten werden aber geliefert ...
BG

**Comment by greenMikeEU** [comment]
Kann ich das als gelöst ansehen ? IoBroker hat ja nichts mit meinem Projekt zu tun.

**Comment by Daffy2905** [comment]
JaVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: greenMike ***@***.***> Datum: 11.05.23  21:29  (GMT+01:00) An: greenMikeEU/SmartMeterEVNSagemcom-T210-D ***@***.***> Cc: Daffy2905 ***@***.***>, Author ***@***.***> Betreff: Re: [greenMikeEU/SmartMeterEVNSagemcom-T210-D] Fehler in V2.0 (Issue #20) 
Kann ich das als gelöst ansehen ? IoBroker hat ja nichts mit meinem Projekt zu tun.
