### ISSUE TITLE
Unix Time Stamp

### ISSUE THREAD

**Issue by breiti93** [greenMikeEU/SmartMeterEVNSagemcom-T210-D#21]
Hallo,

Bei mir crasht nach einige Zeit das Pyhton Skript.
Wäre es möglich das ich per MQTT den Unix Timestamp bekomme..dann würde ich zumindest einen Crash schneller feststellen und kann reagieren bis ich den Fehler gefunden habe?

Danke und lg

**Comment by breiti93** [comment]
Hallo nochmals,
ich habe das Ausleseskript einfach um eine Zeile erweitert:

 client.publish("Smartmeter/Timestamp",int(time.time()))
 
 Löst aktuell mal mein "Problem"
 Falls du das für die Zukunft einbauen möchtest.

lg

**Comment by greenMikeEU** [comment]
Ich werde es in Zukunft mal einbauen
