### ISSUE TITLE
Meter-ID in XML

### ISSUE THREAD

**Issue by pkolmann** [greenMikeEU/SmartMeterEVNSagemcom-T210-D#4]
Liebe Mitstreidende,

ich hab mich am Wochenende mit dem Script gespielt und bin schwer begeistert wie gut das mit meinem Smart-Meter geht.

Ich will nun aus dem XML auch die Smart-Meter-ID auslesen, welche laut EVN Dokument ab StringPosition 462 stehen sollte.

Bei mir schaut das auch für die ersten 4 Byte gut aus, dann kommt plötzlich kauderwelsch, welches bei jedem Auslesen sich verändert.

```
313738324201e010f8
31373832db3388c76c
3137383287190746e3
31373832b7b1e5dafe
31373832aae41f921c
```

Alle Anderen Werte schauen gut aus, insofern habe ich den EVN Key nicht im Visier.

Wie schaut das bei euch aus? Habt ihr die vollständige Zählernummer im XML drin?

Danke,
lg Philipp

**Comment by greenMikeEU** [comment]
Hallo,

ich finde ihre Arbeit sehr interessant. Können Sie mir eine Mail schreiben ? 
mreitbauer@gmx.net
LG Michael
